<!-- Generated by Trae Work -->
<template>
  <div class="evolution-page">
    <!-- 顶部统计卡片 -->
    <el-row :gutter="16">
      <el-col :span="6">
        <div class="stat-card">
          <div class="stat-label">
            <span style="display:flex;align-items:center;gap:4px;">
              <span class="status-light" :class="dashboard.summary.total_verified_signals > 0 ? 'ok' : 'idle'"></span>
              已验证信号
            </span>
          </div>
          <div class="stat-value">{{ dashboard.summary.total_verified_signals }}</div>
          <div class="stat-sub text-dim">样本量</div>
        </div>
      </el-col>
      <el-col :span="6">
        <div class="stat-card win">
          <div class="stat-label">
            <span style="display:flex;align-items:center;gap:4px;">
              <span class="status-light" :class="dashboard.summary.win_rate >= 50 ? 'ok' : 'error'"></span>
              整体胜率
            </span>
          </div>
          <div class="stat-value">{{ dashboard.summary.win_rate }}%</div>
          <div class="stat-sub">
            胜 {{ dashboard.summary.win_signals }} / 亏 {{ dashboard.summary.loss_signals }}
          </div>
        </div>
      </el-col>
      <el-col :span="6">
        <div class="stat-card pattern">
          <div class="stat-label">
            <span style="display:flex;align-items:center;gap:4px;">
              <span class="status-light" :class="dashboard.patterns?.length > 0 ? 'warn' : 'ok'"></span>
              发现模式
            </span>
          </div>
          <div class="stat-value">{{ dashboard.patterns?.length || 0 }}</div>
          <div class="stat-sub text-dim">假信号模式</div>
        </div>
      </el-col>
      <el-col :span="6">
        <div class="stat-card proposal">
          <div class="stat-label">
            <span style="display:flex;align-items:center;gap:4px;">
              <span class="status-light" :class="dashboard.pending_proposals?.length > 0 ? 'warn' : 'ok'"></span>
              待处理方案
            </span>
          </div>
          <div class="stat-value">{{ dashboard.pending_proposals?.length || 0 }}</div>
          <div class="stat-sub text-dim">优化建议</div>
        </div>
      </el-col>
    </el-row>

    <!-- 操作栏 -->
    <div class="action-bar mt-16">
      <el-button type="primary" :loading="running" @click="runEvolution">
        <el-icon><Refresh /></el-icon>
        运行进化分析
      </el-button>
      <span class="text-dim ml-12" v-if="dashboard.last_run">
        上次运行：{{ formatTime(dashboard.last_run.started_at) }} ·
        发现 {{ dashboard.last_run.patterns_found }} 个模式 ·
        生成 {{ dashboard.last_run.proposals_generated }} 个方案
      </span>
    </div>

    <!-- 因子重要性 -->
    <div class="panel-card mt-16">
      <div class="panel-card__header">
        <span class="panel-card__title">
          <el-icon style="color:#60A5FA"><TrendCharts /></el-icon>
          因子重要性排名
        </span>
        <span class="text-dim" style="font-size:12px;">基于历史信号回测计算各因子的预测能力</span>
      </div>
      <div class="panel-card__body">
        <div class="factor-list">
          <div v-for="(f, i) in dashboard.factor_stats" :key="f.factor_name" class="factor-row">
            <div class="factor-rank">{{ i + 1 }}</div>
            <div class="factor-info">
              <div class="factor-name">{{ f.factor_name_cn }}</div>
              <div class="factor-meta">
                <span>准确率 {{ f.accuracy }}%</span>
                <span>相关性 {{ f.correlation }}</span>
                <span>样本 {{ f.sample_size }}</span>
              </div>
            </div>
            <div class="factor-bar">
              <div class="factor-bar-fill" :style="{ width: f.importance_score + '%' }"></div>
            </div>
            <div class="factor-importance">{{ f.importance_score }}</div>
            <div class="factor-weights">
              <span class="text-dim" style="font-size:11px;">当前 {{ (f.current_weight*100).toFixed(0) }}%</span>
              <el-icon v-if="f.suggested_weight > f.current_weight" style="color:#4ADE80;"><ArrowUp /></el-icon>
              <el-icon v-else-if="f.suggested_weight < f.current_weight" style="color:#F87171;"><ArrowDown /></el-icon>
              <span v-if="f.suggested_weight != f.current_weight" style="font-size:11px;" :class="f.suggested_weight > f.current_weight ? 'text-profit' : 'text-loss'">
                建议 {{ (f.suggested_weight*100).toFixed(0) }}%
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 假信号模式 -->
    <div class="panel-card mt-16">
      <div class="panel-card__header">
        <span class="panel-card__title">
          <el-icon style="color:#F87171"><Warning /></el-icon>
          假信号模式识别
        </span>
        <span class="text-dim" style="font-size:12px;">自动挖掘容易导致亏损的信号特征</span>
      </div>
      <div class="panel-card__body">
        <el-table :data="dashboard.patterns" size="small" stripe>
          <el-table-column prop="severity_cn" label="程度" width="90">
            <template #default="{ row }">
              <span style="display:inline-flex;align-items:center;gap:4px;">
                <span class="status-light" :class="row.severity==='critical'||row.severity==='high'?'error':(row.severity==='medium'?'warn':'idle')"></span>
                <el-tag size="small" :type="severityType(row.severity)" effect="dark">
                  {{ row.severity_cn }}
                </el-tag>
              </span>
            </template>
          </el-table-column>
          <el-table-column prop="description" label="模式描述" min-width="200" />
          <el-table-column prop="win_rate" label="胜率" width="90" align="center">
            <template #default="{ row }">
              <span style="display:inline-flex;align-items:center;gap:4px;">
                <span class="status-light" :class="row.win_rate >= 50 ? 'ok' : 'error'"></span>
                <span :class="row.win_rate >= 50 ? 'text-profit' : 'text-loss'">{{ row.win_rate }}%</span>
              </span>
            </template>
          </el-table-column>
          <el-table-column prop="total_signals" label="样本量" width="80" align="center" />
          <el-table-column prop="market_regime" label="市场状态" width="120" align="center">
            <template #default="{ row }">
              <span v-if="row.market_regime" class="regime-tag">{{ regimeCN(row.market_regime) }}</span>
              <span v-else class="text-dim">-</span>
            </template>
          </el-table-column>
          <el-table-column prop="suggestion" label="改进建议" min-width="180" />
        </el-table>
        <div v-if="!dashboard.patterns?.length" class="empty-tip text-dim">
          暂无足够历史信号数据，积累更多已验证信号后自动分析
        </div>
      </div>
    </div>

    <!-- 进化方案 -->
    <div class="panel-card mt-16">
      <div class="panel-card__header">
        <span class="panel-card__title">
          <el-icon style="color:#A78BFA"><MagicStick /></el-icon>
          进化优化方案
        </span>
        <span class="text-dim" style="font-size:12px;">AI基于历史数据自动生成的策略优化建议</span>
      </div>
      <div class="panel-card__body">
        <div class="proposal-list">
          <div v-for="p in dashboard.pending_proposals" :key="p.id" class="proposal-card">
            <div class="proposal-header">
              <el-tag :type="proposalTypeColor(p.proposal_type)" effect="light" size="small">
                <span class="status-light" :class="p.confidence>=70?'ok':(p.confidence>=50?'warn':'error')" style="margin-right:2px;"></span>
                {{ p.proposal_type_cn }}
              </el-tag>
              <span class="proposal-confidence">
                <span class="status-light" :class="p.confidence>=70?'ok':(p.confidence>=50?'warn':'error')" style="margin-right:2px;"></span>
                置信度 {{ p.confidence }}%
              </span>
            </div>
            <div class="proposal-title">{{ p.title }}</div>
            <div class="proposal-desc text-dim">{{ p.description }}</div>

            <div class="proposal-benefits">
              <div class="benefit-item" v-if="p.expected_win_rate_improvement">
                <span class="benefit-label">胜率提升</span>
                <span class="benefit-value text-profit">+{{ p.expected_win_rate_improvement }}%</span>
              </div>
              <div class="benefit-item" v-if="p.expected_profit_factor_improvement">
                <span class="benefit-label">盈亏比提升</span>
                <span class="benefit-value text-profit">+{{ p.expected_profit_factor_improvement }}</span>
              </div>
              <div class="benefit-item" v-if="p.expected_drawdown_reduction">
                <span class="benefit-label">回撤降低</span>
                <span class="benefit-value text-profit">-{{ p.expected_drawdown_reduction }}%</span>
              </div>
            </div>

            <div class="proposal-evidence text-dim" v-if="p.evidence_summary">
              <el-icon><DataAnalysis /></el-icon>
              {{ p.evidence_summary }}
            </div>

            <div class="proposal-actions">
              <el-button type="success" size="small" @click="acceptProposal(p)">
                <el-icon><Check /></el-icon>
                接受
              </el-button>
              <el-button type="danger" size="small" plain @click="rejectProposal(p)">
                <el-icon><Close /></el-icon>
                拒绝
              </el-button>
            </div>
          </div>
        </div>
        <div v-if="!dashboard.pending_proposals?.length" class="empty-tip text-dim">
          暂无待处理的优化方案，点击上方"运行进化分析"生成建议
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { ElMessage } from 'element-plus'
import { Refresh, TrendCharts, Warning, MagicStick, DataAnalysis, Check, Close, ArrowUp, ArrowDown } from '@element-plus/icons-vue'
import { http, API_PREFIX } from '@/utils/request'

const dashboard = ref({
  summary: { total_verified_signals: 0, win_signals: 0, loss_signals: 0, expired_signals: 0, win_rate: 0 },
  patterns: [],
  factor_stats: [],
  pending_proposals: [],
  last_run: null,
})
const running = ref(false)

function severityType(s) {
  return { critical: 'danger', high: 'danger', medium: 'warning', low: 'info' }[s] || 'info'
}

function regimeCN(r) {
  const map = {
    'ranging': '震荡市',
    'strong_trend_up': '强上涨',
    'strong_trend_down': '强下跌',
    'weak_trend_up': '弱上涨',
    'weak_trend_down': '弱下跌',
    'breakout_up': '向上突破',
    'breakout_down': '向下突破',
  }
  return map[r] || r
}

function proposalTypeColor(t) {
  return { weight: 'primary', threshold: 'warning', parameter: 'success', regime_filter: 'info' }[t] || ''
}

function formatTime(t) {
  if (!t) return '-'
  const d = new Date(t)
  return d.toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })
}

async function loadDashboard() {
  try {
    const r = await http.get(`${API_PREFIX}/evolution/dashboard`)
    dashboard.value = r
  } catch (e) {
    // 表可能还没创建，忽略
  }
}

async function runEvolution() {
  running.value = true
  try {
    const r = await http.post(`${API_PREFIX}/evolution/run`)
    ElMessage.success(`进化分析完成：发现${r.patterns_found}个模式，生成${r.proposals_generated}个方案`)
    await loadDashboard()
  } catch (e) {
    ElMessage.error('进化分析失败：' + (e.message || '未知错误'))
  } finally {
    running.value = false
  }
}

async function acceptProposal(p) {
  try {
    await http.post(`${API_PREFIX}/evolution/proposals/${p.id}/accept`)
    ElMessage.success('方案已接受')
    await loadDashboard()
  } catch (e) {
    ElMessage.error('操作失败')
  }
}

async function rejectProposal(p) {
  try {
    await http.post(`${API_PREFIX}/evolution/proposals/${p.id}/reject`)
    ElMessage.info('方案已拒绝')
    await loadDashboard()
  } catch (e) {
    ElMessage.error('操作失败')
  }
}

onMounted(loadDashboard)
</script>

<style scoped>
.evolution-page {
  padding: 16px 20px;
  max-width: 1400px;
  margin: 0 auto;
}

/* 统计卡片 */
.stat-card {
  background: var(--el-fill-color-light);
  border-radius: 10px;
  padding: 16px 20px;
  border-left: 3px solid var(--border-color);
}
.stat-card.win { border-left-color: #4ADE80; }
.stat-card.pattern { border-left-color: #F87171; }
.stat-card.proposal { border-left-color: #A78BFA; }

.stat-label {
  font-size: 13px;
  color: var(--text-secondary);
  margin-bottom: 6px;
}
.stat-value {
  font-size: 28px;
  font-weight: 700;
  color: var(--text-primary);
  font-variant-numeric: tabular-nums;
}
.stat-sub {
  font-size: 12px;
  margin-top: 4px;
}

/* 操作栏 */
.action-bar {
  display: flex;
  align-items: center;
}

/* 因子重要性 */
.factor-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.factor-row {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 8px 12px;
  background: var(--el-fill-color-lighter);
  border-radius: 6px;
}
.factor-rank {
  width: 24px;
  height: 24px;
  border-radius: 50%;
  background: var(--el-fill-color);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  font-weight: 600;
  flex-shrink: 0;
}
.factor-row:nth-child(1) .factor-rank { background: #FBBF24; color: #000; }
.factor-row:nth-child(2) .factor-rank { background: #94A3B8; color: #fff; }
.factor-row:nth-child(3) .factor-rank { background: #D97706; color: #fff; }

.factor-info {
  width: 140px;
  flex-shrink: 0;
}
.factor-name {
  font-size: 13px;
  font-weight: 600;
  color: var(--text-primary);
}
.factor-meta {
  display: flex;
  gap: 8px;
  font-size: 11px;
  color: var(--text-dim);
  margin-top: 2px;
}

.factor-bar {
  flex: 1;
  height: 8px;
  background: var(--el-fill-color);
  border-radius: 4px;
  overflow: hidden;
}
.factor-bar-fill {
  height: 100%;
  background: linear-gradient(90deg, #60A5FA, #A78BFA);
  border-radius: 4px;
  transition: width 0.5s ease;
}

.factor-importance {
  width: 40px;
  text-align: right;
  font-size: 13px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
}

.factor-weights {
  width: 110px;
  display: flex;
  align-items: center;
  gap: 4px;
  justify-content: flex-end;
  flex-shrink: 0;
}

/* 假信号模式 */
.empty-tip {
  text-align: center;
  padding: 30px 0;
  font-size: 13px;
}
.regime-tag {
  font-size: 11px;
  padding: 2px 8px;
  background: var(--el-fill-color);
  border-radius: 4px;
}

/* 进化方案 */
.proposal-list {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  gap: 12px;
}
.proposal-card {
  background: var(--el-fill-color-lighter);
  border-radius: 8px;
  padding: 14px;
  border: 1px solid var(--border-color);
  transition: all 0.2s;
}
.proposal-card:hover {
  border-color: var(--el-color-primary-light-5);
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}
.proposal-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 8px;
}
.proposal-confidence {
  font-size: 12px;
  color: var(--text-secondary);
  font-weight: 500;
}
.proposal-title {
  font-size: 15px;
  font-weight: 600;
  color: var(--text-primary);
  margin-bottom: 6px;
}
.proposal-desc {
  font-size: 12px;
  line-height: 1.5;
  margin-bottom: 10px;
}
.proposal-benefits {
  display: flex;
  gap: 16px;
  padding: 8px 0;
  border-top: 1px solid var(--border-color-lighter);
  border-bottom: 1px solid var(--border-color-lighter);
  margin-bottom: 8px;
}
.benefit-item {
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.benefit-label {
  font-size: 11px;
  color: var(--text-dim);
}
.benefit-value {
  font-size: 14px;
  font-weight: 700;
}
.proposal-evidence {
  font-size: 11px;
  display: flex;
  align-items: center;
  gap: 4px;
  margin-bottom: 10px;
  line-height: 1.4;
}
.proposal-actions {
  display: flex;
  gap: 8px;
}
</style>
